spring:
  application:
    name: 'Backend'
  datasource:
    url: jdbc:postgresql://localhost:5432/database
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  main:
    banner-mode: off
  output:
    ansi:
      enabled: always
server:
  port: 8080
logging:
  pattern:
    dateformat: hh:mm:ss