openapi: 3.0.3
info:
  version: 1.0.0
  title: Backend API
  description: Description
servers:
  - url: http://api.backend.com/
    description: Server description
paths:
  /accounts:
    get:
      tags:
        - Accounts
      operationId: getAccounts
      description: Returns a list of accounts
      responses:
        '200':
          description: Successfully returned a list of accounts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Account'

        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Account:
      type: object
      required:
        - id
        - role
        - email
        - name
        - password
        - birthday
        - capital
      properties:
        id:
          type: integer
        role:
          type: string
        email:
          type: string
        name:
          type: string
        password:
          type: string
        birthday:
          type: string
        capital:
          type: integer
    Error:
      type: object
      properties:
        message:
          type: string

