openapi: 3.0.3

info:
  version: 1.0.0
  title: Backend API
  description: Description

servers:
  - url: https://api.backend.com/
    description: Server description

paths:
  /accounts:
    get:
      tags:
        - Accounts
      operationId: getAllAccounts
      description: Returns a list of accounts
      responses:
        '200':
          description: Successfully returned a list of accounts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AccountODTO'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      tags:
        - Accounts
      operationId: createAccount
      description: Creates a new account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createAccountIDTO'
      responses:
        '200':
          description: Successfully created a new artist
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountODTO'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    AccountODTO:
      type: object
      required:
        - id
        - role
        - email
        - name
        - password
        - birthday
        - capital
      properties:
        id:
          type: integer
        role:
          $ref: '#/components/schemas/RoleDTO'
        email:
          type: string
        name:
          type: string
        password:
          type: string
        birthday:
          type: string
          format: date
        capital:
          type: integer
    createAccountIDTO:
      type: object
      required:
        - role
        - email
        - name
        - password
        - birthday
        - capital
      properties:
        role:
          $ref: '#/components/schemas/RoleDTO'
        email:
          type: string
        name:
          type: string
        password:
          type: string
        birthday:
          type: string
          format: date
        capital:
          type: integer
    RoleDTO:
      type: string
      enum: [ admin, user, guest ]
    Error:
      type: object
      properties:
        message:
          type: string